import Footer from "@/components/Footer";
import Accueil from "@/components/home/FirstSection";
import FourthSection from "@/components/home/FourthSection";
import SecondSection from "@/components/home/SecondSection";
import SixthSection from "@/components/home/SixthSection";
import ThirdSection from "@/components/home/ThirdSection";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import FifthSection from "../components/home/FifthSection";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Accueil />
        <SecondSection />
        <ThirdSection />
        <FourthSection />
        <FifthSection />
        {/* {children} */}
        <SixthSection />
        <Footer />
      </body>
    </html>
  );
}
